
  const textResources = {
    he: {
        // General
        direction: 'rtl',
        return: 'חזור',
        cancel: 'ביטול',
        areYouSure: 'האם אתה בטוח?',
        sending: 'שולח',
        sendNow: 'שלח',
        employeeNotExist: 'עובד לא נמצא במערכת',
        notSuccess: 'לא הצליח',
        reortNotCreated: 'דיווח לא נוצר',
        workspaceError: 'יש בעיה עם העמדה, אנה התחבר מחדש',
        InvalidOperation: 'סוג הפעולה לא תקינה',
        generalError: 'שגיאה במהלך הביצוע',
        // Login
        workspaceNumber: 'מספר עמדה',
        enterNumWorkspace: 'הכנס מספר עמדה',
        login: 'התחבר',
        wait: 'המתן',
        // Dashboard
        name: 'שם',
        serialNum: 'מספר סידורי',
        status: 'סטטוס',
        currentStation: 'תחנה נוכחית',
        produced: 'יוצרו',
        packed: 'נארזו',
        ordered: 'הוזמנו',
        openedDate: 'תאריך פתיחה',
        startSession: 'תחילת עבודה',
        endSession: 'סיום ודיווח',
        send: 'שליחה',
        dashboardFilter: 'חפש לפי מספר סידורי...',
        station: 'עמדת',
        storage: 'מחסן',
        production: 'יצור',
        packing: 'אריזה',
        // Sliderbar
        paka: 'פקעו"ת',
        queue: 'תור',
        settings: 'הגדרות',
        quit: 'יציאה',
        // Error Page
        error: 'שגיאה',
        errorPageMessage: 'אירעה שגיאה במערכת. אנא נסה להתחבר מחדש',
        loginBack: 'התחבר מחדש',
        // Not Found
        pageNotFound404: '404 - דף לא קיים',
        pageNotFoundOps: 'אופס! הדף לא קיים',
        returnMainPage: 'חזרה לעמוד הראשי',
        // Storage
        enterNumberComponent: 'הכנס מספר רכיב...',
        enterQuantity: 'הכנס כמות...',
        comments: 'הערות',
        filterComponentByNameOrNumber: 'חפש רכיב לפי שם או מספר...',
        componentNum: 'מספר רכיב',
        quantity: 'כמות',
        componentList: 'רשימת הרכיבים',
        addComponentNum: 'הכנס מספר רכיב...',
        addQuantity: 'הכנס כמות',
        addComponent: 'הוסף רכיב',
        sendReporting: 'שלח דיווח',
        showReportComponents: 'הצג רכיבים בהזמנה',
        addComponentsInDB: 'כל הרכיבים במערכת',
        filterByComponentNum: 'חפש לפי מספר רכיב',
        // Comments Modal
        notAvailableComponents: 'אין הערות זמינות',
        // Components Modal
        componentList: 'רשימת רכיבים',
        // Production & Packing
        catalogNumber: 'מקט',
        good: 'תקינים',
        quantitySize: 'כמות יחידות',
        showComments: 'הצג הערות',
        enterCatalogNum: 'הכנס מקט',
        // Settings
        chooseLanguage: 'בחר שפה',
        // Session Modal
        sendReport: 'שליחה לתחנה הבאה',
        receiveReport: 'קבלה לתחנה הנוכחית',
        employeeNum: 'מספר עובד',
        enterEmployeeNum: 'הכנס מספר עובד',
    },
    en: {
        // General
        direction: 'ltr',
        return: 'Return',
        cancel: 'Cancel',
        areYouSure: 'Are you sure?',
        sending: 'Sending',
        sendNow: 'Send',
        employeeNotExist: 'Employee does not exist in the system',
        notSuccess: 'Operation was not successful',
        reportNotCreated: 'Report was not created',
        workspaceError: 'There is an issue with the workspace, please reconnect',
        InvalidOperation: 'The operation type is invalid',
        generalError: 'Error occurred during execution',
        // Login
        workspaceNumber: 'Workspace number',
        enterNumWorkspace: 'Enter workspace number',
        login: 'Login',
        wait: 'Wait',
        // Dashboard
        name: 'Name',
        serialNum: 'Serial number',
        status: 'Status',
        currentStation: 'Current workspace',
        produced: 'Produced',
        packed: 'Packed',
        ordered: 'Ordered',
        openedDate: 'Opened date',
        startSession: 'Start session',
        endSession: 'End & Report',
        send: 'Send',
        dashboardFilter: 'Seach by serial number...',
        station: 'Workspace',
        storage: 'Storage',
        production: 'Production',
        packing: 'Packing',
        // Sliderbar
        paka: 'Work orders',
        queue: 'Queue',
        settings: 'Settings',
        quit: 'Quit',
        // Error Page
        error: 'Error',
        errorPageMessage: 'A system error has occurred. Please try logging in again.',
        loginBack: 'Login back',
        // Not Found
        pageNotFound404: 'Page not found - 404',
        pageNotFoundOps: 'Oops! The page does not exist.',
        returnMainPage: 'Back to main page',
        // Storage
        enterNumberComponent: 'Enter component number...',
        enterQuantity: 'Enter quantity...',
        comments: 'Comments',
        filterComponentByNameOrNumber: 'Search for a component by name or number...',
        componentNum: 'Component number',
        quantity: 'Quantity',
        componentList: 'Component list',
        addComponentNum: 'Enter component number...',
        addQuantity: 'Enter quantity',
        addComponent: 'Add a component',
        sendReporting: 'Send a report',
        showReportComponents: 'Show components on order',
        addComponentsInDB: 'All components in the system',
        filterByComponentNum: 'Search by component number',
        // Comments Modal
        notAvailableComponents: 'No comments available',
        // Components Modal
        componentList: 'List of components',
        // Production & Packing
        catalogNumber: 'Catalog number',
        good: 'OK',
        quantitySize: 'Quantity of units',
        showComments: 'Sow comments',
        enterCatalogNum: 'Enter catalog number',
        // Settings
        chooseLanguage: 'choose language',
        // Session Modal
        sendReport: 'Send to the next station',
        receiveReport: 'Receive at the current station',
        employeeNum: 'Employee Number',
        enterEmployeeNum: 'Enter Employee Number',
    },
    ru: {
        return: 'возврат',
        cancel: 'отмена',
        areYouSure: 'Вы уверены?',
        sending: 'отправка',
        sendNow: 'отправить',
        employeeNotExist: 'Сотрудник не найден в системе',
        notSuccess: 'Операция не удалась',
        reportNotCreated: 'Отчет не создан',
        workspaceError: 'Проблема с рабочим местом, пожалуйста, переподключитесь',
        InvalidOperation: 'Тип операции недействителен',
        generalError: 'Произошла ошибка при выполнении',
        // Login
        workspaceNumber: 'Номер рабочего места',
        enterNumWorkspace: 'Введите номер рабочего места',
        login: 'Войти',
        wait: 'Ожидание',
        // Dashboard
        name: 'Имя',
        serialNum: 'Серийный номер',
        status: 'Статус',
        currentStation: 'Текущая рабочая станция',
        produced: 'Произведено',
        packed: 'Упаковано',
        ordered: 'Заказано',
        openedDate: 'Дата открытия',
        startSession: 'Начать сессию',
        endSession: 'Завершить и Отчет',
        send: 'Отправить',
        dashboardFilter: 'Поиск по серийному номеру...',
        station: 'Рабочая станция',
        storage: 'Склад',
        production: 'Производство',
        packing: 'Упаковка',
        // Sliderbar
        paka: 'Рабочие заказы',
        queue: 'Очередь',
        settings: 'Настройки',
        quit: 'Выйти',
        // Error Page
        error: 'Ошибка',
        errorPageMessage: 'Произошла системная ошибка. Пожалуйста, попробуйте войти снова.',
        loginBack: 'Вернуться ко входу',
        // Not Found
        pageNotFound404: 'Страница не найдена - 404',
        pageNotFoundOps: 'Упс! Страница не существует.',
        returnMainPage: 'Вернуться на главную страницу',
        // Storage
        enterNumberComponent: 'Введите номер компонента...',
        enterQuantity: 'Введите количество...',
        comments: 'Комментарии',
        filterComponentByNameOrNumber: 'Поиск компонента по названию или номеру...',
        componentNum: 'Номер компонента',
        quantity: 'Количество',
        componentList: 'Список компонентов',
        addComponentNum: 'Введите номер компонента...',
        addQuantity: 'Введите количество',
        addComponent: 'Добавить компонент',
        sendReporting: 'Отправить отчет',
        showReportComponents: 'Показать компоненты в заказе',
        addComponentsInDB: 'Все компоненты в системе',
        filterByComponentNum: 'Поиск по номеру компонента',
        // Comments Modal
        notAvailableComponents: 'Комментарии недоступны',
        // Components Modal
        componentList: 'Список компонентов',
        // Production & Packing
        catalogNumber: 'Каталожный номер',
        good: 'ОК',
        quantitySize: 'Количество единиц',
        showComments: 'Показать комментарии',
        enterCatalogNum: 'Введите каталожный номер',
        // Settings
        chooseLanguage: 'выберите язык',
        // Session Modal
        sendReport: 'Отправить на следующую станцию',
        receiveReport: 'Получить на текущей станции',
        employeeNum: 'Номер сотрудника',
        enterEmployeeNum: 'Введите номер сотрудника',
        },

};

const localStorageStrings = [
    'workspace',
    'employee_number',
    'reportId',
    'serialNum',
    'total',
    'completed',


]
  export { textResources, localStorageStrings }
